function isElementInViewport(elem){if(elem||elem==null){return false;}
var bounding=elem.getBoundingClientRect();return(bounding.top>=0&&bounding.left>=0&&bounding.bottom<=(window.innerHeight||document.documentElement.clientHeight)&&bounding.right<=(window.innerWidht||document.documentElement.clientWidth));};function isAnyPartOfElementInViewport(elem){if(!elem||elem==null){return false;}
const rect=elem.getBoundingClientRect();const windowHeight=(window.innerHeight||document.documentElement.clientHeight);const windowWidth=(window.innerWidth||document.documentElement.clientWidht);const vertInView=(rect.top<=windowHeight)&&((rect.top+rect.height)>=0);const horInView=(rect.top<=windowWidth)&&((rect.left+rect.width)>=0);return(vertInView&&horInView);}
window.dataLayer=window.dataLayer||[];window.addEventListener('DOMContentLoaded',function(){var mainBottomNav=document.getElementById('main_bottom_nav');var contentNews=document.querySelector('.content-news');var tagBola=document.querySelector('.tagbola');});var menuFooterObserverHandlerExecuted=false;function menuFooterObserverHandler(entries,observer){for(entry of entries){if(entry.isIntersecting&&!menuFooterObserverHandlerExecuted){dataLayerPushImpression("menu-footer","bottom");menuFooterObserverHandlerExecuted=true;}}}
var TagBolaObserverHandlerExecuted=false;function TagBolaObserverHandler(entries,observer){for(entry of entries){if(entry.isIntersecting&&!TagBolaObserverHandlerExecuted){dataLayerPushImpression("article-tags","bottom");TagBolaObserverHandlerExecuted=true;}}}
var relatedNewsObserverHandlerExecuted=false;function relatedNewsObserverHandler(entries,observer){for(entry of entries){if(entry.isIntersecting&&!relatedNewsObserverHandlerExecuted){dataLayerPushImpression("related","bottom");relatedNewsObserverHandlerExecuted=true;}}}
var gatewayLiputan6ObserverHandlerExecuted=false;function gatewayLiputan6ObserverHandler(entries,observer){for(entry of entries){if(entry.isIntersecting&&!gatewayLiputan6ObserverHandlerExecuted){dataLayerPushImpression('gateway-liputan','bottom');gatewayLiputan6ObserverHandlerExecuted=true;}}}
function latestUpdateObserverHandler(entries,observer){for(entry of entries){if(entry.isIntersecting){dataLayerPushImpression('latest-update','bottom');}}}
var latestEditorialObserverHandlerExecuted=false;function latestEditorialObserverHandler(entries,observer){for(entry of entries){if(entry.isIntersecting&&!latestEditorialObserverHandlerExecuted){dataLayerPushImpression('latest-editorial','bottom');latestEditorialObserverHandlerExecuted=true;}}}
var relatedContentWidgetObserverExecuted=false;function relatedContentWidgetObserver(entries,observer){for(entry of entries){if(entry.isIntersecting&&!relatedContentWidgetObserverExecuted){dataLayerPushImpression('baca-juga','center');relatedContentWidgetObserverExecuted=true;}}}
var otherEditorialRelatedArticleObserverExecuted=false;function otherEditorialRelatedArticleObserverHandler(entries,observer){for(entry of entries){if(entry.isIntersecting&&!otherEditorialRelatedArticleObserverExecuted){dataLayerPushImpression('other-editorial','bottom');otherEditorialRelatedArticleObserverExecuted=true;}}}
function handlePaginationIntersect(entries,observer){entries.forEach(function(entry){var pageIsExecuted=entry.target.dataset.pageObserverIsExecuted;if(entry.isIntersecting&&pageIsExecuted=='false'){entry.target.dataset.pageObserverIsExecuted='true';dataLayerPageView(window.location.pathname+"?Page="+entry.target.dataset.page);}});}
function dataLayerPushImpression(name,location){dataLayer.push({event:"impression",feature_name:name,feature_location:location});}
function dataLayerPushClick(name,location,position,kanalPage){dataLayer.push({event:"click",feature_name:name,feature_location:location,feature_position:position,kanal_page:kanalPage});}
function dataLayerPageView(path){dataLayer.push({'event':'virtual_page_view','virtual_pageview_path':path,});}
let menuFooterElmentObserver=new IntersectionObserver(menuFooterObserverHandler);let tagBolaElementObserver=new IntersectionObserver(TagBolaObserverHandler);let relatedNewsElementObserver=new IntersectionObserver(relatedNewsObserverHandler);let gatewayLiputan6ElementObserver=new IntersectionObserver(gatewayLiputan6ObserverHandler);let latestEditorialElementObserver=new IntersectionObserver(latestEditorialObserverHandler);let relatedContentWidgetElementObserver=new IntersectionObserver(relatedContentWidgetObserver);let latestUpdateElementObserver=new IntersectionObserver(latestUpdateObserverHandler);let otherEditorialRelatedArticleElementObserver=new IntersectionObserver(otherEditorialRelatedArticleObserverHandler);let menuFooter=document.getElementById("main_bottom_nav");menuFooterElmentObserver.observe(menuFooter);let tagBolaEl=document.getElementsByClassName("tagbola");if(tagBolaEl.length>0){tagBolaElementObserver.observe(tagBolaEl[0]);}
let relatedNews=document.getElementsByClassName("related-news-container");if(relatedNews.length>0){relatedNewsElementObserver.observe(relatedNews[0]);}
let gatewayLiputan6=document.getElementsByClassName("gateaway-liputan");if(gatewayLiputan6.length>0){gatewayLiputan6ElementObserver.observe(gatewayLiputan6[0]);}
let latestUpdate=document.getElementsByClassName("latest-update-title");if(latestUpdate.length>0){latestUpdateElementObserver.observe(latestUpdate[0]);}
let latestEditorial=document.getElementsByClassName("latest-editorial-title");if(latestEditorial.length>0){latestEditorialElementObserver.observe(latestEditorial[0]);}
let relatedContentWidget=document.getElementById('related-content-widget');if(relatedContentWidget){relatedContentWidgetElementObserver.observe(relatedContentWidget);}
let otherEditorialRelatedArticleWidget=document.getElementById("other_editorial_related_article");if(otherEditorialRelatedArticleWidget){otherEditorialRelatedArticleElementObserver.observe(otherEditorialRelatedArticleWidget);}
var HomepageHighlightObserverHandlerExecuted=false;function HomepageHighlightObserverHandler(entries,observer){for(entry of entries){if(entry.isIntersecting&&!HomepageHighlightObserverHandlerExecuted){dataLayerPushImpression("highlight","top");HomepageHighlightObserverHandlerExecuted=true;}}}
let HomepageHighlightObserver=new IntersectionObserver(HomepageHighlightObserverHandler);let HomepageHighlight=document.getElementById("homepage-highlight");if(HomepageHighlight){HomepageHighlightObserver.observe(HomepageHighlight);}
var HomepageHeadlineObserverHandlerExecuted=false;function HomepageHeadlineObserverHandler(entries,observer){for(entry of entries){if(entry.isIntersecting&&!HomepageHeadlineObserverHandlerExecuted){dataLayerPushImpression("headline","top");HomepageHeadlineObserverHandlerExecuted=true;}}}
let HomepageHeadlineObserver=new IntersectionObserver(HomepageHeadlineObserverHandler);let HomepageHeadline=document.getElementById("headlines-box");if(HomepageHeadline){HomepageHeadlineObserver.observe(HomepageHeadline);}
var trendingTagObserverHandlerExecuted=false;function trendingTagObserverHandler(entries,observer){for(entry of entries){if(entry.isIntersecting&&!trendingTagObserverHandlerExecuted){dataLayerPushImpression("trending-tag","center","","");trendingTagObserverHandlerExecuted=true;}}}
let trendingTag=document.getElementById("trending-tags");let trendingTagObserver=new IntersectionObserver(trendingTagObserverHandler);if(trendingTag){trendingTagObserver.observe(trendingTag);}
var homepageLatestNewsObserverHandlerExecuted=false;function homepageLatestNewsObserverHandler(entries,observer){for(entry of entries){if(entry.isIntersecting&&!homepageLatestNewsObserverHandlerExecuted){dataLayerPushImpression("latest-news","center","","");homepageLatestNewsObserverHandlerExecuted=true;}}}
let homepageLatestNews=document.getElementById("main_mid_lastest_list");let homepageLatestNewsObserver=new IntersectionObserver(homepageLatestNewsObserverHandler);if(homepageLatestNews){homepageLatestNewsObserver.observe(homepageLatestNews);}
var homepageMostViewedObserverHandlerExecuted=false;function homepageMostViewedObserverHandler(entries,observer){for(entry of entries){if(entry.isIntersecting&&!homepageMostViewedObserverHandlerExecuted){dataLayerPushImpression("populer","center","","");homepageMostViewedObserverHandlerExecuted=true;}}}
let homepageMostViewed=document.getElementById("main_mid_most_viewed_content");let homepageMostViewedObserver=new IntersectionObserver(homepageMostViewedObserverHandler);if(homepageMostViewed){homepageMostViewedObserver.observe(homepageMostViewed);}
var homepageBolatainmentObserverHandlerExecuted=false;function homepageBolatainmentObserverHandler(entries,observer){for(entry of entries){if(entry.isIntersecting&&!homepageBolatainmentObserverHandlerExecuted){dataLayerPushImpression("bolatainment","bottom","","");homepageBolatainmentObserverHandlerExecuted=true;}}}
let homepageBolatainment=document.getElementById("main_mid_bolatainment_list");let homepageBolatainmentObserver=new IntersectionObserver(homepageBolatainmentObserverHandler);if(homepageBolatainment){homepageBolatainmentObserver.observe(homepageBolatainment);}
var homepageSpecialSoccerObserverHandlerExecuted=false;function homepageSpecialSoccerObserverHandler(entries,observer){for(entry of entries){if(entry.isIntersecting&&!homepageSpecialSoccerObserverHandlerExecuted){dataLayerPushImpression("editorial","bottom","","");homepageSpecialSoccerObserverHandlerExecuted=true;}}}
let homepageSpecialSoccer=document.getElementById("main_mid_special_soccer_list");let homepageSpecialSoccerObserver=new IntersectionObserver(homepageSpecialSoccerObserverHandler);if(homepageSpecialSoccer){homepageSpecialSoccerObserver.observe(homepageSpecialSoccer);}
let targetPagination=document.querySelectorAll('#list-pagination');if(targetPagination){var optionPagination={threshold:0.1};paginationObserver=new IntersectionObserver(handlePaginationIntersect,optionPagination);targetPagination.forEach(pages=>{paginationObserver.observe(pages);});}